version: '2'

services:
  php:
    build:
      context: php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - "${APP_PATH}:/var/www/app"
    ports:
        - 9000:9000
    links:
      - db
    environment:
        WORDPRESS_HOST: ${WORDPRESS_DB_HOST}
        WORDPRESS_DATABASE: ${WORDPRESS_DB_NAME}
        WORDPRESS_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        WORDPRESS_CONFIG_EXTRA: ${CONFIG_EXTRA}  

  db:
    image: mysql    
    restart: always
    volumes:
      - "./db-data:/var/lib/mysql"
    user: mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}      

  http:
      build: nginx
      ports:
        - 80:80
      volumes_from:
        - php
      links:
        - php
      depends_on:
        - php    
      volumes:
        - ./logs/nginx/:/var/log/nginx